2019-12-16 19:25:18.864|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 4988 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:25:18.881|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:25:19.490|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:25:19.527|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@52f27fbd: startup date [Mon Dec 16 19:25:19 CST 2019]; root of context hierarchy
2019-12-16 19:25:20.665|WARN ||o.m.s.m.ClassPathMapperScanner|No MyBatis mapper was found in '[com.zxp]' package. Please check your configuration.
2019-12-16 19:25:22.407|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:25:22.429|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:25:22.433|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:25:22.646|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:25:22.647|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 3120 ms
2019-12-16 19:25:23.000|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/]
2019-12-16 19:25:23.009|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:25:23.010|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:25:23.010|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:25:23.010|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:25:23.125|WARN ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userControler': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'userMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.zxp.mapper.UserMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2019-12-16 19:25:23.128|INFO ||o.a.c.c.StandardService|Stopping service [Tomcat]
2019-12-16 19:25:23.179|INFO ||o.s.b.a.l.AutoConfigurationReportLoggingInitializer|

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-12-16 19:25:23.354|ERROR||o.s.b.d.LoggingFailureAnalysisReporter|

***************************
APPLICATION FAILED TO START
***************************

Description:

Field userMapper in com.zxp.service.UserService required a bean of type 'com.zxp.mapper.UserMapper' that could not be found.


Action:

Consider defining a bean of type 'com.zxp.mapper.UserMapper' in your configuration.

2019-12-16 19:25:45.252|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 3204 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:25:45.257|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:25:45.760|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@52f27fbd: startup date [Mon Dec 16 19:25:45 CST 2019]; root of context hierarchy
2019-12-16 19:25:45.865|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:25:46.669|WARN ||o.m.s.m.ClassPathMapperScanner|No MyBatis mapper was found in '[com.zxp]' package. Please check your configuration.
2019-12-16 19:25:48.237|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:25:48.265|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:25:48.267|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:25:48.480|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:25:48.480|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2720 ms
2019-12-16 19:25:48.770|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/]
2019-12-16 19:25:48.779|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:25:48.780|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:25:48.780|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:25:48.780|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:25:48.891|WARN ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userControler': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'userMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.zxp.mapper.UserMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2019-12-16 19:25:48.893|INFO ||o.a.c.c.StandardService|Stopping service [Tomcat]
2019-12-16 19:25:48.937|INFO ||o.s.b.a.l.AutoConfigurationReportLoggingInitializer|

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-12-16 19:25:49.128|ERROR||o.s.b.d.LoggingFailureAnalysisReporter|

***************************
APPLICATION FAILED TO START
***************************

Description:

Field userMapper in com.zxp.service.UserService required a bean of type 'com.zxp.mapper.UserMapper' that could not be found.


Action:

Consider defining a bean of type 'com.zxp.mapper.UserMapper' in your configuration.

2019-12-16 19:28:00.718|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 2624 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:28:00.722|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:28:01.194|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:28:01 CST 2019]; root of context hierarchy
2019-12-16 19:28:01.349|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:28:02.025|WARN ||o.m.s.m.ClassPathMapperScanner|No MyBatis mapper was found in '[com.zxp]' package. Please check your configuration.
2019-12-16 19:28:03.348|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:28:03.370|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:28:03.372|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:28:03.523|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:28:03.524|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2330 ms
2019-12-16 19:28:03.733|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/]
2019-12-16 19:28:03.740|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:28:03.741|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:28:03.741|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:28:03.742|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:28:03.808|WARN ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userControler': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'userMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.zxp.mapper.UserMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2019-12-16 19:28:03.813|INFO ||o.a.c.c.StandardService|Stopping service [Tomcat]
2019-12-16 19:28:03.849|INFO ||o.s.b.a.l.AutoConfigurationReportLoggingInitializer|

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-12-16 19:28:04.028|ERROR||o.s.b.d.LoggingFailureAnalysisReporter|

***************************
APPLICATION FAILED TO START
***************************

Description:

Field userMapper in com.zxp.service.UserService required a bean of type 'com.zxp.mapper.UserMapper' that could not be found.


Action:

Consider defining a bean of type 'com.zxp.mapper.UserMapper' in your configuration.

2019-12-16 19:28:29.220|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 1232 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:28:29.223|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:28:29.674|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:28:29 CST 2019]; root of context hierarchy
2019-12-16 19:28:29.767|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:28:30.500|WARN ||o.m.s.m.ClassPathMapperScanner|No MyBatis mapper was found in '[com.zxp]' package. Please check your configuration.
2019-12-16 19:28:31.845|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:28:31.865|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:28:31.867|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:28:32.045|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:28:32.046|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2372 ms
2019-12-16 19:28:32.266|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/]
2019-12-16 19:28:32.272|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:28:32.273|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:28:32.274|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:28:32.274|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:28:32.358|WARN ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userControler': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'userMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.zxp.mapper.UserMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2019-12-16 19:28:32.362|INFO ||o.a.c.c.StandardService|Stopping service [Tomcat]
2019-12-16 19:28:32.408|INFO ||o.s.b.a.l.AutoConfigurationReportLoggingInitializer|

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-12-16 19:28:32.559|ERROR||o.s.b.d.LoggingFailureAnalysisReporter|

***************************
APPLICATION FAILED TO START
***************************

Description:

Field userMapper in com.zxp.service.UserService required a bean of type 'com.zxp.mapper.UserMapper' that could not be found.


Action:

Consider defining a bean of type 'com.zxp.mapper.UserMapper' in your configuration.

2019-12-16 19:30:27.452|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 3800 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:30:27.456|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:30:27.967|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:30:27 CST 2019]; root of context hierarchy
2019-12-16 19:30:28.003|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:30:28.790|WARN ||o.m.s.m.ClassPathMapperScanner|No MyBatis mapper was found in '[com.zxp]' package. Please check your configuration.
2019-12-16 19:30:30.129|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:30:30.152|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:30:30.154|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:30:30.324|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:30:30.325|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2357 ms
2019-12-16 19:30:30.544|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/]
2019-12-16 19:30:30.551|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:30:30.552|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:30:30.553|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:30:30.553|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:30:30.635|WARN ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userControler': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'userMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.zxp.mapper.UserMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2019-12-16 19:30:30.639|INFO ||o.a.c.c.StandardService|Stopping service [Tomcat]
2019-12-16 19:30:30.685|INFO ||o.s.b.a.l.AutoConfigurationReportLoggingInitializer|

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-12-16 19:30:30.844|ERROR||o.s.b.d.LoggingFailureAnalysisReporter|

***************************
APPLICATION FAILED TO START
***************************

Description:

Field userMapper in com.zxp.service.UserService required a bean of type 'com.zxp.mapper.UserMapper' that could not be found.


Action:

Consider defining a bean of type 'com.zxp.mapper.UserMapper' in your configuration.

2019-12-16 19:30:39.537|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 1160 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:30:39.540|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:30:40.017|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3745e5c6: startup date [Mon Dec 16 19:30:40 CST 2019]; root of context hierarchy
2019-12-16 19:30:40.058|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:30:40.827|WARN ||o.m.s.m.ClassPathMapperScanner|No MyBatis mapper was found in '[com.zxp]' package. Please check your configuration.
2019-12-16 19:30:42.578|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:30:42.595|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:30:42.597|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:30:42.750|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:30:42.751|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2734 ms
2019-12-16 19:30:42.948|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/]
2019-12-16 19:30:42.955|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:30:42.958|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:30:42.958|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:30:42.958|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:30:43.034|WARN ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userControler': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'userMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.zxp.mapper.UserMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2019-12-16 19:30:43.037|INFO ||o.a.c.c.StandardService|Stopping service [Tomcat]
2019-12-16 19:30:43.077|INFO ||o.s.b.a.l.AutoConfigurationReportLoggingInitializer|

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-12-16 19:30:43.215|ERROR||o.s.b.d.LoggingFailureAnalysisReporter|

***************************
APPLICATION FAILED TO START
***************************

Description:

Field userMapper in com.zxp.service.UserService required a bean of type 'com.zxp.mapper.UserMapper' that could not be found.


Action:

Consider defining a bean of type 'com.zxp.mapper.UserMapper' in your configuration.

2019-12-16 19:30:49.042|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 3696 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:30:49.045|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:30:49.514|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:30:49 CST 2019]; root of context hierarchy
2019-12-16 19:30:49.604|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:30:50.343|WARN ||o.m.s.m.ClassPathMapperScanner|No MyBatis mapper was found in '[com.zxp]' package. Please check your configuration.
2019-12-16 19:30:51.864|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:30:51.887|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:30:51.890|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:30:52.072|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:30:52.073|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2559 ms
2019-12-16 19:30:52.290|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/]
2019-12-16 19:30:52.296|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:30:52.297|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:30:52.297|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:30:52.298|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:30:52.387|WARN ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userControler': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'userMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.zxp.mapper.UserMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2019-12-16 19:30:52.390|INFO ||o.a.c.c.StandardService|Stopping service [Tomcat]
2019-12-16 19:30:52.438|INFO ||o.s.b.a.l.AutoConfigurationReportLoggingInitializer|

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-12-16 19:30:52.587|ERROR||o.s.b.d.LoggingFailureAnalysisReporter|

***************************
APPLICATION FAILED TO START
***************************

Description:

Field userMapper in com.zxp.service.UserService required a bean of type 'com.zxp.mapper.UserMapper' that could not be found.


Action:

Consider defining a bean of type 'com.zxp.mapper.UserMapper' in your configuration.

2019-12-16 19:31:56.889|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 2376 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:31:56.892|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:31:57.338|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:31:57 CST 2019]; root of context hierarchy
2019-12-16 19:31:57.366|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:31:58.217|WARN ||o.m.s.m.ClassPathMapperScanner|No MyBatis mapper was found in '[com.zxp]' package. Please check your configuration.
2019-12-16 19:31:59.651|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:31:59.675|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:31:59.677|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:31:59.867|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:31:59.868|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2531 ms
2019-12-16 19:32:00.068|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/]
2019-12-16 19:32:00.075|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:32:00.076|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:32:00.076|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:32:00.077|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:32:00.160|WARN ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userControler': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'userMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.zxp.mapper.UserMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2019-12-16 19:32:00.165|INFO ||o.a.c.c.StandardService|Stopping service [Tomcat]
2019-12-16 19:32:00.219|INFO ||o.s.b.a.l.AutoConfigurationReportLoggingInitializer|

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-12-16 19:32:00.360|ERROR||o.s.b.d.LoggingFailureAnalysisReporter|

***************************
APPLICATION FAILED TO START
***************************

Description:

Field userMapper in com.zxp.service.UserService required a bean of type 'com.zxp.mapper.UserMapper' that could not be found.


Action:

Consider defining a bean of type 'com.zxp.mapper.UserMapper' in your configuration.

2019-12-16 19:33:14.952|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 1276 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:33:14.956|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:33:15.354|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:33:15 CST 2019]; root of context hierarchy
2019-12-16 19:33:15.557|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:33:17.575|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:33:17.590|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:33:17.591|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:33:17.723|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:33:17.724|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2371 ms
2019-12-16 19:33:17.932|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/]
2019-12-16 19:33:17.939|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:33:17.940|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:33:17.940|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:33:17.940|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:33:18.993|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerAdapter|Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:33:15 CST 2019]; root of context hierarchy
2019-12-16 19:33:19.095|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/fileUpload]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.FileUploadControler.fileUpload(org.springframework.web.multipart.MultipartFile) throws java.lang.IllegalStateException,java.io.IOException
2019-12-16 19:33:19.099|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/hello]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.HelloControler.showHelloWorld()
2019-12-16 19:33:19.109|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/adduser],methods=[POST]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.addUser()
2019-12-16 19:33:19.109|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/getall],methods=[GET]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.getUserList()
2019-12-16 19:33:19.113|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-12-16 19:33:19.114|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-12-16 19:33:19.163|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:33:19.164|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:33:19.235|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:33:19.308|WARN ||o.t.t.TemplateMode|[THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-16 19:33:19.872|INFO ||o.s.b.a.w.WebMvcAutoConfiguration$WelcomePageHandlerMapping|Adding welcome page: ServletContext resource [/index.html]
2019-12-16 19:33:20.165|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Registering beans for JMX exposure on startup
2019-12-16 19:33:20.168|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Bean with name 'dataSource' has been autodetected for JMX exposure
2019-12-16 19:33:20.175|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Located MBean 'dataSource': registering with JMX server as MBean [com.alibaba.druid.pool:name=dataSource,type=DruidDataSource]
2019-12-16 19:33:20.197|INFO ||o.a.c.h.Http11NioProtocol|Initializing ProtocolHandler ["http-nio-8080"]
2019-12-16 19:33:20.216|INFO ||o.a.c.h.Http11NioProtocol|Starting ProtocolHandler ["http-nio-8080"]
2019-12-16 19:33:20.241|INFO ||o.a.t.u.n.NioSelectorPool|Using a shared selector for servlet write/read
2019-12-16 19:33:20.270|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat started on port(s): 8080 (http)
2019-12-16 19:33:20.278|INFO ||c.z.SpringMainServer|Started SpringMainServer in 5.684 seconds (JVM running for 6.311)
2019-12-16 19:33:39.622|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-12-16 19:33:39.623|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization started
2019-12-16 19:33:39.651|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization completed in 28 ms
2019-12-16 19:33:39.685|INFO ||c.z.s.UserService|enter UserService selectUserList
2019-12-16 19:33:39.782|INFO ||c.a.d.p.DruidDataSource|{dataSource-1} inited
2019-12-16 19:33:40.030|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.041|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.051|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.057|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.061|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.067|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.074|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.082|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.086|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.090|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.093|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.097|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.104|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.116|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.119|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.129|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.133|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.139|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.149|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.152|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.157|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.162|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.167|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.171|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.179|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.183|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.187|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.194|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.202|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.206|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:33:40.211|ERROR||c.a.d.p.DruidDataSource|create connection error
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1844)
2019-12-16 19:34:13.508|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 4208 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:34:13.510|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:34:14.013|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:34:14 CST 2019]; root of context hierarchy
2019-12-16 19:34:14.078|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:34:16.171|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:34:16.190|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:34:16.192|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:34:16.352|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:34:16.353|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2340 ms
2019-12-16 19:34:16.572|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/]
2019-12-16 19:34:16.579|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:34:16.580|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:34:16.580|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:34:16.580|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:34:17.469|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerAdapter|Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:34:14 CST 2019]; root of context hierarchy
2019-12-16 19:34:17.704|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/fileUpload]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.FileUploadControler.fileUpload(org.springframework.web.multipart.MultipartFile) throws java.lang.IllegalStateException,java.io.IOException
2019-12-16 19:34:17.707|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/hello]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.HelloControler.showHelloWorld()
2019-12-16 19:34:17.717|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/getall],methods=[GET]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.getUserList()
2019-12-16 19:34:17.718|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/adduser],methods=[POST]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.addUser()
2019-12-16 19:34:17.721|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-12-16 19:34:17.722|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-12-16 19:34:17.779|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:34:17.779|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:34:17.849|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:34:17.934|WARN ||o.t.t.TemplateMode|[THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-16 19:34:18.392|INFO ||o.s.b.a.w.WebMvcAutoConfiguration$WelcomePageHandlerMapping|Adding welcome page: ServletContext resource [/index.html]
2019-12-16 19:34:18.743|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Registering beans for JMX exposure on startup
2019-12-16 19:34:18.747|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Bean with name 'dataSource' has been autodetected for JMX exposure
2019-12-16 19:34:18.754|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Located MBean 'dataSource': registering with JMX server as MBean [com.alibaba.druid.pool:name=dataSource,type=DruidDataSource]
2019-12-16 19:34:18.779|INFO ||o.a.c.h.Http11NioProtocol|Initializing ProtocolHandler ["http-nio-8080"]
2019-12-16 19:34:18.807|INFO ||o.a.c.h.Http11NioProtocol|Starting ProtocolHandler ["http-nio-8080"]
2019-12-16 19:34:18.830|INFO ||o.a.t.u.n.NioSelectorPool|Using a shared selector for servlet write/read
2019-12-16 19:34:18.857|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat started on port(s): 8080 (http)
2019-12-16 19:34:18.864|INFO ||c.z.SpringMainServer|Started SpringMainServer in 5.717 seconds (JVM running for 6.328)
2019-12-16 19:34:44.936|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-12-16 19:34:44.936|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization started
2019-12-16 19:34:44.961|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization completed in 25 ms
2019-12-16 19:35:47.555|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 3704 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:35:47.558|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:35:48.047|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:35:48 CST 2019]; root of context hierarchy
2019-12-16 19:35:48.128|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:35:50.323|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:35:50.351|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:35:50.353|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:35:50.561|INFO ||o.a.c.c.C.[.[.[/zxp]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:35:50.562|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2514 ms
2019-12-16 19:35:50.878|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/]
2019-12-16 19:35:50.886|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:35:50.887|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:35:50.887|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:35:50.888|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:35:52.276|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerAdapter|Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:35:48 CST 2019]; root of context hierarchy
2019-12-16 19:35:52.551|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/fileUpload]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.FileUploadControler.fileUpload(org.springframework.web.multipart.MultipartFile) throws java.lang.IllegalStateException,java.io.IOException
2019-12-16 19:35:52.563|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/hello]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.HelloControler.showHelloWorld()
2019-12-16 19:35:52.575|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/adduser],methods=[POST]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.addUser()
2019-12-16 19:35:52.584|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/getall],methods=[GET]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.getUserList()
2019-12-16 19:35:52.587|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-12-16 19:35:52.587|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-12-16 19:35:52.654|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:35:52.654|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:35:52.748|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:35:52.834|WARN ||o.t.t.TemplateMode|[THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-16 19:35:53.284|INFO ||o.s.b.a.w.WebMvcAutoConfiguration$WelcomePageHandlerMapping|Adding welcome page: ServletContext resource [/index.html]
2019-12-16 19:35:53.631|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Registering beans for JMX exposure on startup
2019-12-16 19:35:53.635|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Bean with name 'dataSource' has been autodetected for JMX exposure
2019-12-16 19:35:53.648|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Located MBean 'dataSource': registering with JMX server as MBean [com.alibaba.druid.pool:name=dataSource,type=DruidDataSource]
2019-12-16 19:35:53.681|INFO ||o.a.c.h.Http11NioProtocol|Initializing ProtocolHandler ["http-nio-8080"]
2019-12-16 19:35:53.710|INFO ||o.a.c.h.Http11NioProtocol|Starting ProtocolHandler ["http-nio-8080"]
2019-12-16 19:35:53.762|INFO ||o.a.t.u.n.NioSelectorPool|Using a shared selector for servlet write/read
2019-12-16 19:35:53.813|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat started on port(s): 8080 (http)
2019-12-16 19:35:53.828|INFO ||c.z.SpringMainServer|Started SpringMainServer in 6.654 seconds (JVM running for 7.283)
2019-12-16 19:35:55.403|INFO ||o.a.c.c.C.[.[.[/zxp]|Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-12-16 19:35:55.404|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization started
2019-12-16 19:35:55.441|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization completed in 37 ms
2019-12-16 19:37:22.289|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 3700 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:37:22.292|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:37:22.783|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:37:22 CST 2019]; root of context hierarchy
2019-12-16 19:37:22.806|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:37:25.058|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:37:25.080|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:37:25.082|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:37:25.257|INFO ||o.a.c.c.C.[.[.[/zxp]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:37:25.258|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2475 ms
2019-12-16 19:37:25.490|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/zxptest/*]
2019-12-16 19:37:25.497|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:37:25.498|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:37:25.499|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:37:25.499|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:37:26.427|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerAdapter|Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:37:22 CST 2019]; root of context hierarchy
2019-12-16 19:37:26.703|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/fileUpload]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.FileUploadControler.fileUpload(org.springframework.web.multipart.MultipartFile) throws java.lang.IllegalStateException,java.io.IOException
2019-12-16 19:37:26.705|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/hello]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.HelloControler.showHelloWorld()
2019-12-16 19:37:26.715|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/adduser],methods=[POST]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.addUser()
2019-12-16 19:37:26.716|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/getall],methods=[GET]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.getUserList()
2019-12-16 19:37:26.719|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-12-16 19:37:26.720|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-12-16 19:37:26.786|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:37:26.787|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:37:26.847|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:37:26.919|WARN ||o.t.t.TemplateMode|[THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-16 19:37:27.368|INFO ||o.s.b.a.w.WebMvcAutoConfiguration$WelcomePageHandlerMapping|Adding welcome page: ServletContext resource [/index.html]
2019-12-16 19:37:27.769|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Registering beans for JMX exposure on startup
2019-12-16 19:37:27.776|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Bean with name 'dataSource' has been autodetected for JMX exposure
2019-12-16 19:37:27.783|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Located MBean 'dataSource': registering with JMX server as MBean [com.alibaba.druid.pool:name=dataSource,type=DruidDataSource]
2019-12-16 19:37:27.816|INFO ||o.a.c.h.Http11NioProtocol|Initializing ProtocolHandler ["http-nio-8080"]
2019-12-16 19:37:27.842|INFO ||o.a.c.h.Http11NioProtocol|Starting ProtocolHandler ["http-nio-8080"]
2019-12-16 19:37:27.867|INFO ||o.a.t.u.n.NioSelectorPool|Using a shared selector for servlet write/read
2019-12-16 19:37:27.897|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat started on port(s): 8080 (http)
2019-12-16 19:37:27.908|INFO ||c.z.SpringMainServer|Started SpringMainServer in 5.961 seconds (JVM running for 6.56)
2019-12-16 19:37:42.200|INFO ||o.a.c.c.C.[.[.[/zxp]|Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-12-16 19:37:42.200|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization started
2019-12-16 19:37:42.229|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization completed in 29 ms
2019-12-16 19:38:40.833|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 364 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 19:38:40.837|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 19:38:41.268|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:38:41 CST 2019]; root of context hierarchy
2019-12-16 19:38:41.355|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 19:38:43.493|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 19:38:43.516|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 19:38:43.518|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 19:38:43.703|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 19:38:43.703|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2435 ms
2019-12-16 19:38:43.937|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/zxptest/*]
2019-12-16 19:38:43.946|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 19:38:43.947|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 19:38:43.947|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 19:38:43.947|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 19:38:44.850|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerAdapter|Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 19:38:41 CST 2019]; root of context hierarchy
2019-12-16 19:38:45.117|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/fileUpload]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.FileUploadControler.fileUpload(org.springframework.web.multipart.MultipartFile) throws java.lang.IllegalStateException,java.io.IOException
2019-12-16 19:38:45.120|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/hello]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.HelloControler.showHelloWorld()
2019-12-16 19:38:45.134|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/adduser],methods=[POST]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.addUser()
2019-12-16 19:38:45.135|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/getall],methods=[GET]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.getUserList()
2019-12-16 19:38:45.138|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-12-16 19:38:45.139|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-12-16 19:38:45.201|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:38:45.201|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:38:45.273|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 19:38:45.352|WARN ||o.t.t.TemplateMode|[THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-16 19:38:45.743|INFO ||o.s.b.a.w.WebMvcAutoConfiguration$WelcomePageHandlerMapping|Adding welcome page: ServletContext resource [/index.html]
2019-12-16 19:38:46.064|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Registering beans for JMX exposure on startup
2019-12-16 19:38:46.066|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Bean with name 'dataSource' has been autodetected for JMX exposure
2019-12-16 19:38:46.073|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Located MBean 'dataSource': registering with JMX server as MBean [com.alibaba.druid.pool:name=dataSource,type=DruidDataSource]
2019-12-16 19:38:46.094|INFO ||o.a.c.h.Http11NioProtocol|Initializing ProtocolHandler ["http-nio-8080"]
2019-12-16 19:38:46.112|INFO ||o.a.c.h.Http11NioProtocol|Starting ProtocolHandler ["http-nio-8080"]
2019-12-16 19:38:46.127|INFO ||o.a.t.u.n.NioSelectorPool|Using a shared selector for servlet write/read
2019-12-16 19:38:46.155|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat started on port(s): 8080 (http)
2019-12-16 19:38:46.165|INFO ||c.z.SpringMainServer|Started SpringMainServer in 5.692 seconds (JVM running for 6.312)
2019-12-16 19:38:52.929|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-12-16 19:38:52.929|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization started
2019-12-16 19:38:52.949|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization completed in 19 ms
2019-12-16 20:05:33.877|INFO ||c.z.s.UserService|enter UserService selectUserList
2019-12-16 20:05:33.973|INFO ||c.a.d.p.DruidDataSource|{dataSource-1} inited
2019-12-16 20:05:51.038|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 1600 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 20:05:51.042|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 20:05:51.491|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 20:05:51 CST 2019]; root of context hierarchy
2019-12-16 20:05:51.575|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 20:05:53.808|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 20:05:53.830|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 20:05:53.832|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 20:05:54.002|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 20:05:54.003|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2512 ms
2019-12-16 20:05:54.223|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/zxp/*]
2019-12-16 20:05:54.230|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 20:05:54.231|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 20:05:54.231|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 20:05:54.231|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 20:05:55.324|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerAdapter|Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 20:05:51 CST 2019]; root of context hierarchy
2019-12-16 20:05:55.614|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/fileUpload]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.FileUploadControler.fileUpload(org.springframework.web.multipart.MultipartFile) throws java.lang.IllegalStateException,java.io.IOException
2019-12-16 20:05:55.617|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/hello]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.HelloControler.showHelloWorld()
2019-12-16 20:05:55.627|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/adduser],methods=[POST]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.addUser()
2019-12-16 20:05:55.628|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/getall],methods=[GET]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.getUserList()
2019-12-16 20:05:55.631|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-12-16 20:05:55.632|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-12-16 20:05:55.679|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 20:05:55.679|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 20:05:55.738|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 20:05:55.814|WARN ||o.t.t.TemplateMode|[THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-16 20:05:56.229|INFO ||o.s.b.a.w.WebMvcAutoConfiguration$WelcomePageHandlerMapping|Adding welcome page: ServletContext resource [/index.html]
2019-12-16 20:05:56.571|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Registering beans for JMX exposure on startup
2019-12-16 20:05:56.574|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Bean with name 'dataSource' has been autodetected for JMX exposure
2019-12-16 20:05:56.581|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Located MBean 'dataSource': registering with JMX server as MBean [com.alibaba.druid.pool:name=dataSource,type=DruidDataSource]
2019-12-16 20:05:56.605|INFO ||o.a.c.h.Http11NioProtocol|Initializing ProtocolHandler ["http-nio-8080"]
2019-12-16 20:05:56.625|INFO ||o.a.c.h.Http11NioProtocol|Starting ProtocolHandler ["http-nio-8080"]
2019-12-16 20:05:56.646|INFO ||o.a.t.u.n.NioSelectorPool|Using a shared selector for servlet write/read
2019-12-16 20:05:56.670|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat started on port(s): 8080 (http)
2019-12-16 20:05:56.677|INFO ||c.z.SpringMainServer|Started SpringMainServer in 6.002 seconds (JVM running for 6.631)
2019-12-16 20:06:00.920|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-12-16 20:06:00.920|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization started
2019-12-16 20:06:00.943|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization completed in 23 ms
2019-12-16 20:06:10.606|INFO ||c.z.s.UserService|enter UserService selectUserList
2019-12-16 20:06:10.702|INFO ||c.a.d.p.DruidDataSource|{dataSource-1} inited
2019-12-16 20:07:51.197|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 556 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 20:07:51.204|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 20:07:51.731|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@52f27fbd: startup date [Mon Dec 16 20:07:51 CST 2019]; root of context hierarchy
2019-12-16 20:07:51.767|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 20:07:54.394|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 20:07:54.421|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 20:07:54.424|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 20:07:54.664|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 20:07:54.664|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2933 ms
2019-12-16 20:07:54.939|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/zxp/*]
2019-12-16 20:07:54.949|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 20:07:54.950|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 20:07:54.950|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 20:07:54.950|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 20:07:56.204|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerAdapter|Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@52f27fbd: startup date [Mon Dec 16 20:07:51 CST 2019]; root of context hierarchy
2019-12-16 20:07:56.506|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/fileUpload]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.FileUploadControler.fileUpload(org.springframework.web.multipart.MultipartFile) throws java.lang.IllegalStateException,java.io.IOException
2019-12-16 20:07:56.509|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/hello]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.HelloControler.showHelloWorld()
2019-12-16 20:07:56.519|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/adduser],methods=[POST]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.addUser()
2019-12-16 20:07:56.520|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/getall],methods=[GET]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.getUserList()
2019-12-16 20:07:56.523|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-12-16 20:07:56.524|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-12-16 20:07:56.589|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 20:07:56.589|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 20:07:56.680|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 20:07:56.778|WARN ||o.t.t.TemplateMode|[THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-16 20:07:57.214|INFO ||o.s.b.a.w.WebMvcAutoConfiguration$WelcomePageHandlerMapping|Adding welcome page: ServletContext resource [/index.html]
2019-12-16 20:07:57.930|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Registering beans for JMX exposure on startup
2019-12-16 20:07:57.933|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Bean with name 'dataSource' has been autodetected for JMX exposure
2019-12-16 20:07:57.942|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Located MBean 'dataSource': registering with JMX server as MBean [com.alibaba.druid.pool:name=dataSource,type=DruidDataSource]
2019-12-16 20:07:57.968|INFO ||o.a.c.h.Http11NioProtocol|Initializing ProtocolHandler ["http-nio-8080"]
2019-12-16 20:07:57.991|INFO ||o.a.c.h.Http11NioProtocol|Starting ProtocolHandler ["http-nio-8080"]
2019-12-16 20:07:58.014|INFO ||o.a.t.u.n.NioSelectorPool|Using a shared selector for servlet write/read
2019-12-16 20:07:58.066|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat started on port(s): 8080 (http)
2019-12-16 20:07:58.083|INFO ||c.z.SpringMainServer|Started SpringMainServer in 7.282 seconds (JVM running for 8.083)
2019-12-16 20:08:03.184|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-12-16 20:08:03.184|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization started
2019-12-16 20:08:03.213|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization completed in 29 ms
2019-12-16 20:08:03.256|INFO ||c.z.c.UserControler|controls  start getUserList 
2019-12-16 20:08:03.257|INFO ||c.z.s.UserService|enter UserService selectUserList
2019-12-16 20:08:03.389|INFO ||c.a.d.p.DruidDataSource|{dataSource-1} inited
2019-12-16 20:09:15.942|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 2808 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 20:09:15.945|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 20:09:16.393|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 20:09:16 CST 2019]; root of context hierarchy
2019-12-16 20:09:16.514|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 20:09:24.738|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 5544 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 20:09:24.742|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 20:09:25.218|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 20:09:25 CST 2019]; root of context hierarchy
2019-12-16 20:09:25.301|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 20:09:27.456|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 20:09:27.478|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 20:09:27.480|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 20:09:27.719|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 20:09:27.720|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2502 ms
2019-12-16 20:09:27.941|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/zxp/*]
2019-12-16 20:09:27.946|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 20:09:27.947|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 20:09:27.947|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 20:09:27.948|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 20:09:28.928|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerAdapter|Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@60611244: startup date [Mon Dec 16 20:09:25 CST 2019]; root of context hierarchy
2019-12-16 20:09:29.211|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/fileUpload]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.FileUploadControler.fileUpload(org.springframework.web.multipart.MultipartFile) throws java.lang.IllegalStateException,java.io.IOException
2019-12-16 20:09:29.213|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/hello]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.HelloControler.showHelloWorld()
2019-12-16 20:09:29.223|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/adduser],methods=[POST]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.addUser()
2019-12-16 20:09:29.223|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/getall],methods=[GET]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.getUserList()
2019-12-16 20:09:29.226|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-12-16 20:09:29.227|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-12-16 20:09:29.279|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 20:09:29.279|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 20:09:29.344|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 20:09:29.408|WARN ||o.t.t.TemplateMode|[THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-16 20:09:29.801|INFO ||o.s.b.a.w.WebMvcAutoConfiguration$WelcomePageHandlerMapping|Adding welcome page: ServletContext resource [/index.html]
2019-12-16 20:09:30.158|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Registering beans for JMX exposure on startup
2019-12-16 20:09:30.161|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Bean with name 'dataSource' has been autodetected for JMX exposure
2019-12-16 20:09:30.167|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Located MBean 'dataSource': registering with JMX server as MBean [com.alibaba.druid.pool:name=dataSource,type=DruidDataSource]
2019-12-16 20:09:30.189|INFO ||o.a.c.h.Http11NioProtocol|Initializing ProtocolHandler ["http-nio-8080"]
2019-12-16 20:09:30.210|INFO ||o.a.c.h.Http11NioProtocol|Starting ProtocolHandler ["http-nio-8080"]
2019-12-16 20:09:30.233|INFO ||o.a.t.u.n.NioSelectorPool|Using a shared selector for servlet write/read
2019-12-16 20:09:30.262|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat started on port(s): 8080 (http)
2019-12-16 20:09:30.267|INFO ||c.z.SpringMainServer|Started SpringMainServer in 5.888 seconds (JVM running for 6.497)
2019-12-16 20:09:37.955|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-12-16 20:09:37.956|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization started
2019-12-16 20:09:37.985|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization completed in 29 ms
2019-12-16 20:09:38.034|INFO ||c.z.c.UserControler|controls  start getUserList 
2019-12-16 20:09:38.034|INFO ||c.z.s.UserService|enter UserService selectUserList
2019-12-16 20:09:38.154|INFO ||c.a.d.p.DruidDataSource|{dataSource-1} inited
2019-12-16 20:10:11.938|INFO ||c.z.SpringMainServer|Starting SpringMainServer on 276L1TOFFTS9ZKY with PID 6056 (E:\springcloudworkspace\SpringBootTest\target\classes started by Administrator in E:\springcloudworkspace\SpringBootTest)
2019-12-16 20:10:11.944|INFO ||c.z.SpringMainServer|No active profile set, falling back to default profiles: default
2019-12-16 20:10:12.431|INFO ||o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext|Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@52f27fbd: startup date [Mon Dec 16 20:10:12 CST 2019]; root of context hierarchy
2019-12-16 20:10:12.559|INFO ||o.h.v.i.u.Version|HV000001: Hibernate Validator 5.3.6.Final
2019-12-16 20:10:15.049|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat initialized with port(s): 8080 (http)
2019-12-16 20:10:15.075|INFO ||o.a.c.c.StandardService|Starting service [Tomcat]
2019-12-16 20:10:15.077|INFO ||o.a.c.c.StandardEngine|Starting Servlet Engine: Apache Tomcat/8.5.27
2019-12-16 20:10:15.257|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring embedded WebApplicationContext
2019-12-16 20:10:15.258|INFO ||o.s.w.c.ContextLoader|Root WebApplicationContext: initialization completed in 2827 ms
2019-12-16 20:10:15.517|INFO ||o.s.b.w.s.ServletRegistrationBean|Mapping servlet: 'dispatcherServlet' to [/zxp/*]
2019-12-16 20:10:15.527|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-16 20:10:15.528|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-16 20:10:15.529|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-16 20:10:15.529|INFO ||o.s.b.w.s.FilterRegistrationBean|Mapping filter: 'requestContextFilter' to: [/*]
2019-12-16 20:10:16.769|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerAdapter|Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@52f27fbd: startup date [Mon Dec 16 20:10:12 CST 2019]; root of context hierarchy
2019-12-16 20:10:17.063|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/fileUpload]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.FileUploadControler.fileUpload(org.springframework.web.multipart.MultipartFile) throws java.lang.IllegalStateException,java.io.IOException
2019-12-16 20:10:17.066|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/hello]}" onto public java.util.Map<java.lang.String, java.lang.Object> com.zxp.controler.HelloControler.showHelloWorld()
2019-12-16 20:10:17.076|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/adduser],methods=[POST]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.addUser()
2019-12-16 20:10:17.078|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/user/getall],methods=[GET]}" onto public java.util.List<com.zxp.po.User> com.zxp.controler.UserControler.getUserList()
2019-12-16 20:10:17.082|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-12-16 20:10:17.083|INFO ||o.s.w.s.m.m.a.RequestMappingHandlerMapping|Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-12-16 20:10:17.162|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 20:10:17.163|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 20:10:17.242|INFO ||o.s.w.s.h.SimpleUrlHandlerMapping|Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-16 20:10:17.326|WARN ||o.t.t.TemplateMode|[THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-16 20:10:17.853|INFO ||o.s.b.a.w.WebMvcAutoConfiguration$WelcomePageHandlerMapping|Adding welcome page: ServletContext resource [/index.html]
2019-12-16 20:10:18.582|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Registering beans for JMX exposure on startup
2019-12-16 20:10:18.586|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Bean with name 'dataSource' has been autodetected for JMX exposure
2019-12-16 20:10:18.594|INFO ||o.s.j.e.a.AnnotationMBeanExporter|Located MBean 'dataSource': registering with JMX server as MBean [com.alibaba.druid.pool:name=dataSource,type=DruidDataSource]
2019-12-16 20:10:18.619|INFO ||o.a.c.h.Http11NioProtocol|Initializing ProtocolHandler ["http-nio-8080"]
2019-12-16 20:10:18.646|INFO ||o.a.c.h.Http11NioProtocol|Starting ProtocolHandler ["http-nio-8080"]
2019-12-16 20:10:18.667|INFO ||o.a.t.u.n.NioSelectorPool|Using a shared selector for servlet write/read
2019-12-16 20:10:18.712|INFO ||o.s.b.c.e.t.TomcatEmbeddedServletContainer|Tomcat started on port(s): 8080 (http)
2019-12-16 20:10:18.722|INFO ||c.z.SpringMainServer|Started SpringMainServer in 7.187 seconds (JVM running for 7.993)
2019-12-16 20:10:26.226|INFO ||o.a.c.c.C.[.[.[/]|Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-12-16 20:10:26.226|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization started
2019-12-16 20:10:26.263|INFO ||o.s.w.s.DispatcherServlet|FrameworkServlet 'dispatcherServlet': initialization completed in 35 ms
2019-12-16 20:10:26.311|INFO ||c.z.c.UserControler|controls  start getUserList 
2019-12-16 20:10:26.312|INFO ||c.z.s.UserService|enter UserService selectUserList
2019-12-16 20:10:26.422|INFO ||c.a.d.p.DruidDataSource|{dataSource-1} inited
